config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

   get 'users/:id/profile', to: 'users#profile', as: :profile
   get 'cars/car_id/bookings', to: 'bookings#confirm'
   post 'cars/car_id/bookings', to: 'bookings#confirm', as: :confirm
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cars do
    resources :bookings, only: [:new, :create, :edit, :update, :show]
  end


  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings

  validates :model, presence: true
  validates :make, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :rate, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :cars
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_car, only: [:show, :new, :create, :edit, :update]
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.car = @car
    if @booking.save
      redirect_to new_car_booking_path(@car, @booking), notice: 'Booking was successfully Created '
    else
      render :new
    end

  end

  # def confirm
  #   @booking = Booking.new(booking_params)
  #   @booking.user = current_user
  #   @booking.car = @car
  #     if @booking.save
  #       redirect_to new_car_booking_path(@@car, @booking), notice: 'Please confirm you booking details '
  #     else
  #      render :new
  #     end
  # end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to car_booking_path(@car, @booking), notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @booking.destroy
      redirect_to profile_path(current_user), notice: 'Booking was successfully deleted.'
    else
      render :destroy
    end
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :car_id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car), notice: 'Car was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to car_path(@car), notice: 'Car was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @car.bookings.empty?
      @car.destroy
      redirect_to profile_path(current_user), notice: 'Car was successfully deleted.'
    else
      redirect_to profile_path(current_user), notice: 'Car cannot be deleted, it has associated bookings.'
    end
  end

  private

  def car_params
    params.require(:car).permit(:make, :model, :category, :description, :rate, :user_id)
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #allow access to only home page without login can add other pages to array.
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:edit, :update]

  def profile
    @bookings = current_user.bookings
    @listings = current_user.cars
  end

  # def edit
  # end

  # def update
  #   if @user.update(user_params)
  #     redirect_to profile_path(current_user), notice: 'User was successfully updated.'
  #   else
  #     render :edit
  #   end
  # end

  # private

  # def set_user
  #   @user = current_user
  # end

  # def user_params
  #   params.require(:user).permit()
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [car, booking] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :start_date, as: :date, html5: true %>
  </div>


  <div class="form-inputs">
    <%= f.input :end_date, as: :date, html5: true %>
  </div>



  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/edit.html.erb
<h1>booking#edit</h1>
<p>Find me in app/views/booking/edit.html.erb</p>
<%= render 'form', car: @car, booking: @booking %>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>
<%= render 'form', car: @car, booking: @booking %>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

<div>
  <ul>
     <li class='list'> <%= @car.model %> <%= @car.make%> <%= @booking.start_date%> <%= @booking.end_date%> <%total = (@booking.end_date - @booking.start_date).to_i * @car.rate%> <%= "Total cost of hire: £#{total}" %></li>
       <%= link_to 'Book anothor Car', new_car_booking_path(@car) %>
  </ul>
</div>

app/views/cars/_form.html.erb
<%= simple_form_for(car) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :make %>
  </div>


  <div class="form-inputs">
    <%= f.input :model %>
  </div>


  <div class="form-inputs">
    <%= f.input :category %>
  </div>

   <div class="form-inputs">
    <%= f.input :description, as: :text %>
  </div>

   <div class="form-inputs">
    <%= f.input :rate, as: :integer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/edit.html.erb
<h1>Cars#edit</h1>
<p>Find me in app/views/cars/edit.html.erb</p>
<%= render 'form', car: @car %>

app/views/cars/index.html.erb
<h1>Cars#index</h1>
<p>Find me in app/views/cars/index.html.erb</p>

<div>
  <ul>
    <%@cars.each do |car|  %>
     <li class='list'> <%= car.model %> <%= car.make%> <%= car.rate%></li>
       <%= link_to 'Book Car', new_car_booking_path(car) %>
    <% end %>
  </ul>
</div>

app/views/cars/new.html.erb
<h1>Cars#new</h1>
<p>Find me in app/views/cars/new.html.erb</p>
<%= render 'form', car: @car %>

app/views/cars/show.html.erb
<h1>Cars#show</h1>
<p>Find me in app/views/cars/show.html.erb</p>


<div>
  <ul>
     <li class='list'> <%= @car.model %> <%= @car.make%> <%= @car.rate%></li>
       <%= link_to 'Book Car', new_car_booking_path(@car) %>
       <%= link_to 'Delete Car', @car, method: :delete, data: { confirm: 'Are you sure?' } %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

    <%= render 'shared/navbar'  %>
    <%= render 'shared/flashes'  %>


    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Hello I am a banner</p>
    <a class="btn btn-flat" href="#">Look for cars now</a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "avatar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/users/profile.html.erb
<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |car| %>
      <tr>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= link_to 'Show', car %></td>
        <td>
           <%= link_to 'Edit', edit_car_path(car) %>
        </td>
        <td>
           <%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <%= link_to 'Add New Car', new_car_path %>

 <br>

 <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Loan Start</th>
      <th>Loan Return</th>
      <th>Make</th>
      <th>Model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.user.name %></td>
        <td><%= booking.end_date %></td>
        <td><%= booking.start_date %></td>
        <td><%= booking.car.make %></td>
        <td><%= booking.car.model %></td>
        <td><%= booking.car.id %></td>
        <td><%= booking.user.id %></td>
        <td><%= link_to 'Show', car_booking_path(booking.car_id, booking) %></td>
        <td><%= link_to 'Edit', edit_car_booking_path(booking.car_id, booking) %></td>
        <td><%= link_to 'Delete', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <%= link_to 'Make New Booking', cars_path %>